server:
  port: 8080

spring:
  application:
    name: customer-service
  mvc:
    log-request-details: true
  flyway:
    url: jdbc:mariadb://localhost:3306/testPerf
    user: testPerf
    password: testPerf
  datasource:
    type: org.mariadb.jdbc.MariaDbDataSource
    name: testPerf
    url: jdbc:mariadb://localhost:3306/testPerf?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: testPerf
    password: testPerf
    driverClassName: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
